routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'HomeController');

Route::resource('home', 'HomeController');

Route::resource('employees', 'EmployeeController');

Route::resource('departments', 'DepartmentController');

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Department;
use App\Employee;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departments = Department::all();
        $employees = Employee::all();

        return view('departments.list', compact('departments'), compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('departments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string'
        ]);

        $department = new Department();
        $department->name = $request->get('name');
        $department->save();
        return redirect('/departments')->with('success', 'Отдел создан!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function edit(Department $department)
    {
        return view('departments.edit', compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Department $department)
    {
        $request->validate([
            'name' => 'required|string'
        ]);

        $department = Department::find($request->input('id'));
        $department->name = $request->get('name');
        $department->save();
        return redirect('/departments')->with('success', 'Информация обновлена!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function destroy(Department $department)
    {
        $department->delete();
        return redirect('/departments')->with('success', 'Отдел удалён!');
    }
}

resources/views/departments/create.blade.php
@extends('layouts.app')
@section('title','Новый отдел')
@section('content')

@section('content')

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{{url('/')}}">Главная</a></li>
          <li>Новый отдел</li>
        </ol>
        <h2>Новый отдел</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <section id="employees" class="employees">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">

                    <h1 class="title">Создать новый отдел</h1>

                    @include('partials.site.errors')

                    <form method="post" action="{{ route('departments.store') }}">

                        @csrf

                        <div class="form-group">
                            <label class="label">Название</label>
                            <div class="control">
                                <input type="text" class="form-control" name="name" value="{{ old('name') }}" class="input" placeholder="Название" required />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="control">
                                <button type="submit" class="btn btn-primary">Создать</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </section>

</main><!-- End #main -->

@endsection

resources/views/departments/edit.blade.php
@extends('layouts.app')
@section('title','Редактирование')
@section('content')

@section('content')

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{{url('/')}}">Главная</a></li>
          <li>Редактирование</li>
        </ol>
        <h2>Изменить информацию об отделе</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <section id="employees" class="employees">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">

                    <h1 class="title">Изменить информацию об отделе</h1>

                    @include('partials.site.errors')

                    <form method="post" action="{{ route('departments.update',$department->id) }}">

                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label class="label">Название</label>
                            <div class="control">
                                <input type="text" class="form-control" name="name" value="{{ $department->name }}" class="input" placeholder="Название" required />
                            </div>
                        </div>

                        <input type="hidden" name="id" value = "{{ $department->id }}">

                        <div class="form-group">
                            <div class="control">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </section>

</main><!-- End #main -->

@endsection

resources/views/departments/list.blade.php
@extends('layouts.app')
@section('title','Отделы')
@section('content')

<main id="main">

  <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{{url('/')}}">Главная</a></li>
          <li>Отделы</li>
        </ol>
        <h2>Отделы</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= departments Section ======= -->
    <section id="departmentslist" class="departments">
      <div class="container-fluid">

        <div class="row">
          <div class="col-lg-12">
            <div class="fl jc-sa ai-c">
                <div class=""><h1>Отделы</h1></div>
                <div class=""><a href="{{ route('departments.create')}}" class="btn btn-primary">Создать</a></div>
            </div>
          </div>
        </div>

        <div class="row">
            <div class="col-sm-12">

              @if ($message = Session::get('success'))
                  <div class="alert alert-success">
                      <p>{{ $message }}</p>
                  </div>
              @endif
              
                <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                          <tr>
                            <td>Название отдела</td>
                            <td>Количество сотрудников отдела</td>
                            <td>Максимальная заработная плата среди сотрудников отдела</td>
                            <td></td>
                            <td></td>
                          </tr>
                      </thead>
                      <tbody>
                          @for($i = 0; $i < count($departments); $i++)
                          <tr>
                              <td>{{$departments[$i]['name']}}</td>
                              @php $x=0; @endphp
                              @foreach($employees as $employee)
                                @php $empldepartments = explode(",", $employee->departments); @endphp
                                @for($m = 0; $m < count($empldepartments); $m++)
                                  @if($empldepartments[$m]==$departments[$i]['id'])
                                    @php $x=$x+1; @endphp
                                  @endif
                                @endfor
                              @endforeach
                              <td>
                                @php echo $x; @endphp
                              </td>
                                @php $salaries=[]; @endphp
                                @foreach($employees as $employee)
                                  @php $empldepartments = explode(",", $employee->departments); @endphp
                                  @for($m = 0; $m < count($empldepartments); $m++)
                                    @if($empldepartments[$m]==$departments[$i]['id'])
                                      @php array_push($salaries, $employee->salary); @endphp
                                    @endif
                                  @endfor
                                @endforeach
                              <td>
                                @if(count($salaries)!==0) 
                                    @php echo max($salaries); @endphp
                                @else 
                                    @php echo '0'; @endphp
                                @endif
                              </td>
                              <td>
                                  <a href="{{ route('departments.edit',$departments[$i]['id'])}}" class="btn btn-primary theme-btn">Редактировать</a>
                              </td>
                              <td>
                                  <form action="{{ route('departments.destroy', $departments[$i]['id'])}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger theme-btn" type="submit" @php if($x!=0) echo 'disabled' @endphp>Удалить</button>
                                  </form>
                              </td>
                          </tr>
                          @endfor
                      </tbody>
                    </table>
                </div>
            <div>
        </div>

      </div>
    </section><!-- End employees Section -->

</main><!-- End #main -->

@endsection