routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'HomeController');

Route::resource('home', 'HomeController');

Route::resource('employees', 'EmployeeController');

Route::resource('departments', 'DepartmentController');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\Department;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all();
        $departments = Department::all();

        return view('employees.list', compact('employees'), compact('departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();

        return view('employees.create', compact('departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'surname' => 'required|string',
            'salary' => 'required|integer',
            'departments' => 'required'
        ]);

        $departments_arr = $request->get('departments');

        $patronymic = '';
        if($request->get('patronymic')===null){
            $patronymic = '';
        }else{
            $patronymic = $request->get('patronymic');
        }

        $employee = new Employee();
        $employee->name = $request->get('name');
        $employee->surname = $request->get('surname');
        $employee->patronymic = $patronymic;
        $employee->sex = $request->get('sex');
        $employee->salary = $request->get('salary');
        $employee->departments = implode(",",$departments_arr);
        $employee->save();
        return redirect('/employees')->with('success', 'Сотрудник создан!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $departments = Department::all();
        // $employee = Employee::find($id);
        return view('employees.edit', compact('employee'), compact('departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
            'surname' => 'required|string',
            'salary' => 'required|integer',
            'departments' => 'required'
        ]);

        $departments_arr = $request->get('departments');

        $patronymic = '';
        if($request->get('patronymic')===null){
            $patronymic = '';
        }else{
            $patronymic = $request->get('patronymic');
        }

        $employee = Employee::find($request->input('id'));
        $employee->name = $request->get('name');
        $employee->surname = $request->get('surname');
        $employee->patronymic = $patronymic;
        $employee->sex = $request->get('sex');
        $employee->salary = $request->get('salary');
        $employee->departments = implode(",",$departments_arr);
        $employee->save();
        
        return redirect('/employees')->with('success', 'Информация обновлена!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return redirect('/employees')->with('success', 'Сотрудник удалён!');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')
@section('title','Новый сотрудник')
@section('content')

@section('content')

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{{url('/')}}">Главная</a></li>
          <li>Новый сотрудник</li>
        </ol>
        <h2>Новый сотрудник</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <section id="employees" class="employees">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">

                    <h1 class="title">Создать нового сотрудника</h1>

                    @include('partials.site.errors')

                    <form method="post" action="{{ route('employees.store') }}">

                        @csrf
                        

                        <div class="form-group">
                            <label class="label">Имя</label>
                            <div class="control">
                                <input type="text" class="form-control" name="name" value="{{ old('name') }}" class="input" placeholder="Имя" required />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="label">Фамилия</label>
                            <div class="control">
                                <input type="text" class="form-control" name="surname" value="{{ old('surname') }}" class="input" placeholder="Фамилия" required />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="label">Отчество</label>
                            <div class="control">
                                <input type="text" class="form-control" name="patronymic" value="{{ old('patronymic') }}" class="input" placeholder="Отчество" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="label">Пол</label>
                            <div class="control">
                                <div class="select">
                                    <select class="form-control" name="sex" required>
                                        <option value="" disabled selected>Выберите пол</option>
                                        <option value="мужской" {{ old('sex') === 'мужской' ? 'selected' : null }}>мужской</option>
                                        <option value="женский" {{ old('sex') === 'женский' ? 'selected' : null }}>женский</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="label">Заработная плата</label>
                            <div class="control">
                                <input type="number" class="form-control" name="salary" value="{{ old('salary') }}" class="input" placeholder="Зарплата" required />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="label">Отделы</label>
                            <div class="control">
                                @foreach ($departments as $department)
                                <div class="checkbox">
                                    <label>
                                      <input type="checkbox" name="departments[]" id="{{ $department->name }}" value="{{ $department->id }}" /> {{ $department->name }}
                                    </label>
                                </div>
                                @endforeach
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="control">
                                <button type="submit" class="btn btn-primary">Создать</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </section>

</main><!-- End #main -->

@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')
@section('title','Редактирование')
@section('content')

@section('content')

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{{url('/')}}">Главная</a></li>
          <li>Редактирование</li>
        </ol>
        <h2>Изменить информацию о сотруднике</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <section id="employees" class="employees">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">

                    <h1 class="title">Изменить информацию о сотруднике</h1>

                    @include('partials.site.errors')

                    <form method="POST" action="{{ route('employees.update',$employee->id) }}">

                        @csrf
                        @method('PUT')
                        

                        <div class="form-group">
                            <label class="label">Имя</label>
                            <div class="control">
                                <input type="text" class="form-control" name="name" value="{{ $employee->name }}" class="input" placeholder="Имя" required />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="label">Фамилия</label>
                            <div class="control">
                                <input type="text" class="form-control" name="surname" value="{{ $employee->surname }}" class="input" placeholder="Фамилия" required />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="label">Отчество</label>
                            <div class="control">
                                <input type="text" class="form-control" name="patronymic" value="{{ $employee->patronymic }}" class="input" placeholder="Отчество" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="label">Пол</label>
                            <div class="control">
                                <div class="select">
                                    <select class="form-control" name="sex" required>
                                        <option value="" disabled selected>Выберите пол</option>
                                        <option value="мужской" {{ $employee->sex === 'мужской' ? 'selected' : null }}>мужской</option>
                                        <option value="женский" {{ $employee->sex === 'женский' ? 'selected' : null }}>женский</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="label">Заработная плата</label>
                            <div class="control">
                                <input type="number" class="form-control" name="salary" value="{{ $employee->salary }}" class="input" placeholder="Зарплата" required />
                            </div>
                        </div>

                          @php
                            $departments_array =  $employee->departments;
                            $departments_arr = explode(",", $departments_array);
                          @endphp

                        <div class="form-group">
                            <label class="label">Отделы</label>
                            <div class="control">
                                @foreach ($departments as $department)
                                <div class="checkbox">
                                    <label>
                                      <input type="checkbox" name="departments[]" id="" value="{{ $department->id }}" {{in_array($department->id, $departments_arr) ? 'checked' : ''}} /> {{ $department->name }}
                                    </label>
                                </div>
                                @endforeach
                            </div>
                        </div>

                        <input type="hidden" name="id" value = "{{ $employee->id }}">

                        <div class="form-group">
                            <div class="control">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </section>

</main><!-- End #main -->

@endsection

resources/views/employees/list.blade.php
@extends('layouts.app')
@section('title','Сотрудники')
@section('content')

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{{url('/')}}">Главная</a></li>
          <li>Сотрудники</li>
        </ol>
        <h2>Сотрудники</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= employees Section ======= -->
    <section id="employeeslist" class="employees">
      <div class="container-fluid">

        <div class="row">
          <div class="col-lg-12">
            <div class="fl jc-sa ai-c">
                <div class=""><h1>Сотрудники</h1></div>
                <div class=""><a href="{{ route('employees.create')}}" class="btn btn-primary">Создать</a></div>
            </div>
          </div>
        </div>

        <div class="row">
            <div class="col-sm-12">

                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                
                <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                          <tr>
                            <td>Имя</td>
                            <td>Фамилия</td>
                            <td>Отчество</td>
                            <td>Пол</td>
                            <td>Заработная плата</td>
                            <td>Названия отделов</td>
                            <td></td>
                            <td></td>
                          </tr>
                      </thead>
                      <tbody>
                          @foreach($employees as $employee)
                          <tr>
                              <td>{{$employee->name}}</td>
                              <td>{{$employee->surname}}</td>
                              <td>{{$employee->patronymic}}</td>
                              <td>{{$employee->sex}}</td>
                              <td>{{$employee->salary}}</td>
                              @php $empldepartments = explode(",", $employee->departments); @endphp
                              @php $arrdepartments=[]; @endphp
                              @for($n = 0; $n < count($empldepartments); $n++)
                                @foreach($departments as $department)
                                  @if($empldepartments[$n]==$department->id)
                                    @php array_push($arrdepartments, $department->name); @endphp
                                  @endif
                                @endforeach
                              @endfor
                              @php $arrdep=implode(",",$arrdepartments); @endphp
                              <td>
                                {{$arrdep}}
                              </td>
                              <td>
                                  <a href="{{ route('employees.edit',$employee->id)}}" class="btn btn-primary theme-btn">Редактировать</a>
                              </td>
                              <td>
                                  <form action="{{ route('employees.destroy', $employee->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger theme-btn" type="submit">Удалить</button>
                                  </form>
                              </td>
                          </tr>
                          @endforeach
                      </tbody>
                    </table>
                </div>
            <div>
        </div>

      </div>
    </section><!-- End employees Section -->

</main><!-- End #main -->

@endsection